apiVersion: v1
kind: Service
metadata:
  name: surveillance-api
  namespace: trade-surveillance
spec:
  selector:
    app: surveillance-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
