apiVersion: v1
kind: Secret
metadata:
  name: surveillance-secrets
  namespace: trade-surveillance
type: Opaque
stringData:
  POSTGRES_URL: ""
  REDIS_URL: ""
  NEO4J_URI: ""
  NEO4J_USER: ""
  NEO4J_PASSWORD: ""
  KAFKA_BOOTSTRAP_SERVERS: ""
  KAFKA_SECURITY_PROTOCOL: "SSL"
  KAFKA_SSL_KEYFILE: ""
  KAFKA_SSL_CERTFILE: ""
  KAFKA_SSL_CAFILE: ""
